import type { Metadata } from "next";
import {  Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const poppins = Inter({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900']
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-dark ">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased relative`}
      >
        <Header />
        
        {children}
        <Footer />
        <div className="-z-10  h-34 overflow-hidden text-center fixed bottom-0  w-full bg-black text-neutral-200 ">
        <p className="text-[clamp(4rem,30vw,14rem)]  -mt-8 sm:-mt-32 font-light ">mango</p>
      </div>
      </body>
    </html>
  );
}
